source $VIMRUNTIME/defaults.vim

let &directory = expand("~/.vimdata/swap")
let &backupdir = expand("~/.vimdata/backup")
let &undodir = expand("~/.vimdata/undo")

if !isdirectory(&directory)
    call mkdir(&directory, "p")
endif
if !isdirectory(&backupdir)
    call mkdir(&backupdir, "p")
endif
if !isdirectory(&undodir)
    call mkdir(&undodir, "p")
endif

set termguicolors
set cursorline
set splitbelow
set backup
set undofile
set expandtab
set hlsearch
set fileformats=unix,dos

colorscheme dracula

let mapleader = " "

noremap <Leader>h <C-W>h
noremap <Leader>j <C-W>j
noremap <Leader>k <C-W>k
noremap <Leader>l <C-W>l
noremap <Leader>x <C-W>x

noremap <Leader>f :FZF<CR>
noremap <Leader>n :nohlsearch<CR>
noremap <Leader>c :helpclose<CR>
noremap <Leader>e :E!<CR>

nmap <silent> <C-k> <Plug>(ale_previous_wrap)
nmap <silent> <C-j> <Plug>(ale_next_wrap)

" Enable completion support
let g:ale_completion_enabled = 1

" Algays show the sign gutter even without no warnings and errors
let g:ale_sign_column_always = 1

" Manually trigger LSP autocomplete and show the menu on C-Space
imap <C-Space> <Plug>(ale_complete)
